name: Build Frontend

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Setup
    uses: glaserL/viasp/.github/workflows/setup.yml@main
    with:
      path: environment.yml
  install:
    name: Install npm dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./frontend/node_modules
          key: node-modules-${{ hashFiles('./frontend/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [ setup, install ]
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: initialize conda
        shell: bash -l {0}
        run: conda init bash
      - name: Activate conda environment
        shell: bash -l {0}
        run: conda activate viasp_CI
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install npm dependencies
        working-directory: ./frontend
        run: npm install
      - name: Building react
        working-directory: ./frontend
        run: npm run build
      - name: Building dash component
        working-directory: ./frontend
        shell: bash -l {0}
        run: python -m build --sdist --wheel --outdir dist/;




