name: Build Frontend

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install npm dependencies
        working-directory: ./frontend
        run: npm install

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        working-directory: ./frontend
        run: python -m pip install -r requirements.txt

      - name: Building react
        working-directory: ./frontend
        run: npm run build
      - name: Building dash component
        working-directory: ./frontend
        run: python -m build --sdist --wheel --outdir dist/;




