name: Publish viASP to PyPi

on:
  push:
    branches: [ main ]
    tags:
      - '*'
jobs:
  testing:
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - name: Print stuff
        run: |
          echo ${{github.tag}}
          echo ${{github.ref_name}}
  backend:
    name: Publish backend
    if: ${{contains(github.ref_name, 'backend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: dawidd6/action-download-artifact@v2 # version from GitHub disallows sharing between workflows
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: frontend.yml
          commit: ${{ github.sha }}
          name: backend-${{ github.sha }}
      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
