name: Publish viASP to PyPi

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - '*'
jobs:
  testing:
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - name: Print stuff
        run: |
          echo ${{github.tag}}
          echo ${{github.ref_name}}
  backend:
    name: Publish backend
    if: ${{contains(github.ref_name, 'backend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: dawidd6/action-download-artifact@v2 # version from GitHub disallows sharing between workflows
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: frontend.yml
          path: dist
          commit: ${{ github.sha }}
          name: backend-${{ github.sha }}
      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
  frontend:
    name: Publish frontend
    if: ${{contains(github.ref_name, 'frontend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: dawidd6/action-download-artifact@v2 # version from GitHub disallows sharing between workflows
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: frontend.yml
          path: dist
          commit: ${{ github.sha }}
          name: backend-${{ github.sha }}
      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
  wrapper:
    name: Publish container
    if: ${{ contains(github.ref_name, 'frontend') || contains(github.ref_name, 'backend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Cache conda env
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
        id: cache
      - name: Building dash component
        working-directory: ./viasp
        run: python -m build --sdist --wheel --outdir dist/;

      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: viasp/dist
