name: Publish viASP to PyPi

on:
  workflow_dispatch:
    inputs:
      frontend:
        type: boolean
        required: true
        description: Publish frontend of main HEAD
      backend:
        type: boolean
        required: true
        description: Publish backend of main HEAD

jobs:
  backend:
    name: Publish backend
    if: ${{ github.event.inputs.backend }}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: dawidd6/action-download-artifact@v2 # version from GitHub disallows sharing between workflows
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build_and_test.yml
          path: dist
          commit: ${{ github.sha }}
          name: backend-${{ github.sha }}
      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_BACKEND_SECRET }}
          repository_url: https://test.pypi.org/legacy/
  frontend:
    name: Publish frontend
    if: ${{ github.event.inputs.frontend }}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: dawidd6/action-download-artifact@v2 # version from GitHub disallows sharing between workflows
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build_and_test.yml
          path: dist
          commit: ${{ github.sha }}
          name: frontend-${{ github.sha }}
      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_DASH_SECRET }}
          repository_url: https://test.pypi.org/legacy/
  wrapper:
    needs: [ frontend, backend ]
    name: Publish container
    if: ${{ github.event.inputs.frontend ||github.event.inputs.backend }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Cache conda env
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
        id: cache
      - name: Building wrapper
        working-directory: ./viasp
        run: python -m build --sdist --wheel --outdir dist/;

      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_VIASP_SECRET }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: viasp/dist
