name: "Setup python"

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  conda:
    name: Setup conda environment
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('${{ inputs.path }}') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: viasp_CI
          channel-priority: strict
          environment-file: ${{ inputs.path }}
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: viasp_CI
          use-mamba: true
      - name: Update environment
        run: mamba env update -f ${{ inputs.path }}
        if: steps.cache.outputs.cache-hit != 'true'
